### ISSUE TITLE
[Fix] 효과음 볼륨 조정

### ISSUE THREAD

**Issue by HyewonKkang** [boostcampwm-2022/web37-ZelloDraw#107]
## 요약
유저가 로비에 입장할 때, 입장벨소리 크기를 줄여요.
color-picker에서 색상 선택할 때는 사운드를 없애요.

## 완료조건
- [x] 입장 벨소리 크기 줄이기
- [x] color-picker 색상 선택 효과음 없애기

**Comment by jayjeong8** [comment]
#126 에서 해결되었어요.
